"""PDF -> chunks (-> index, added on day 3). Assignment §4 reproduction command:

    python -m scripts.ingest data/book.pdf
"""

import json
import statistics as st
import sys
from collections import Counter
from pathlib import Path

from app.core.config import settings
from app.models.chunk import Chunk
from app.rag.chunker import CHAPTER_RANGES, Chunker, mark_duplicates
from app.rag.extractor import PdfExtractor

CHAPTER_NAMES = {1: "Anecdotes", 2: "Quotations", 3: "His Life"}


def save_chunks(chunks: list[Chunk], path: Path = settings.chunks_path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        for chunk in chunks:
            fh.write(chunk.model_dump_json() + "\n")


def load_chunks(path: Path = settings.chunks_path) -> list[Chunk]:
    if not path.exists():
        raise FileNotFoundError(f"{path} is missing — run: python -m scripts.ingest data/book.pdf")
    with path.open(encoding="utf-8") as fh:
        return [Chunk.model_validate_json(line) for line in fh if line.strip()]


def write_stats(chunks: list[Chunk], pairs: int, path: Path = Path("docs/CHUNK_STATS.md")) -> None:
    """Generated, never hand-written — a hand-edited table lies after the next change."""
    path.parent.mkdir(parents=True, exist_ok=True)
    per = Counter(c.chapter for c in chunks)
    lines = [
        "# Chunk statistics",
        "",
        f"Generated by `python -m scripts.ingest {settings.book_path}`. Do not edit by hand.",
        "",
        f"**Total chunks: {len(chunks)}**",
        "",
        "| Chapter | Printed pages | Chunks | Mean chars | Median | Min | Max |",
        "|---|---|---|---|---|---|---|",
    ]
    for chapter, (first, last) in CHAPTER_RANGES.items():
        sizes = [len(c.text) for c in chunks if c.chapter == chapter]
        lines.append(
            f"| Ch{chapter} {CHAPTER_NAMES[chapter]} | {first}–{last} | {per[chapter]} | "
            f"{st.mean(sizes):.0f} | {st.median(sizes):.0f} | {min(sizes)} | {max(sizes)} |"
        )

    all_sizes = sorted(len(c.text) for c in chunks)
    lines += [
        "",
        f"Mean over all chunks: {st.mean(all_sizes):.0f} chars. "
        f"Median: {st.median(all_sizes):.0f}. "
        f"Range: {all_sizes[0]}–{all_sizes[-1]}.",
        "",
        "The 20x spread between chapters is why one chunking rule could not work: Ch2's",
        "untitled one-line quotations and Ch3's multi-page question blocks are different",
        "kinds of object, and each is the unit a reader would cite.",
        "",
        "## Shortest and longest chunks",
        "",
        "| Chunk | Chapter | Pages | Chars | Title |",
        "|---|---|---|---|---|",
    ]
    ranked = sorted(chunks, key=lambda c: len(c.text))
    for chunk in ranked[:3] + ranked[-3:]:
        lines.append(
            f"| `{chunk.id}` | Ch{chunk.chapter} | {chunk.page_label} | {len(chunk.text)} "
            f"| {chunk.title[:60]} |"
        )

    linked = [c for c in chunks if c.duplicates]
    lines += [
        "",
        "## Near-duplicate links (Ch1 ↔ Ch3)",
        "",
        f"{pairs} pairs across {len(linked)} chunks. The book announces these itself: Ch3",
        'opens with "Note: Some anecdotes are repeated in this short biographical sketch."',
        "Both copies are kept — their page numbers differ and a citation must point at a",
        "page the reader can open — and the lower-scoring copy is dropped at retrieval time.",
        "",
        "Links are pairwise, not a shared group label: a single Ch3 block retells up to",
        "four *different* Ch1 anecdotes, so one label would make those four look like",
        "duplicates of each other.",
        "",
        "| Ch3 chunk | Pages | Retells |",
        "|---|---|---|",
    ]
    by_id = {c.id: c for c in chunks}
    for chunk in chunks:
        if chunk.chapter == 3 and chunk.duplicates:
            retold = ", ".join(f"Ch1 `{d}` {by_id[d].title}" for d in chunk.duplicates)
            lines.append(f"| `{chunk.id}` | {chunk.page_label} | {retold} |")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(pdf: Path) -> None:
    pages = PdfExtractor(path=pdf).content_pages()
    print(f"[1/3] extracted {len(pages)} content pages (printed 1–{pages[-1].printed})")

    chunks = Chunker().chunk(pages)
    per = Counter(c.chapter for c in chunks)
    print(f"[2/3] chunked: {' / '.join(f'Ch{c} {per[c]}' for c in sorted(per))} = {len(chunks)}")

    pairs = mark_duplicates(chunks)
    print(f"[3/3] near-duplicate pairs: {pairs}")

    save_chunks(chunks)
    write_stats(chunks, pairs)
    print(f"wrote {settings.chunks_path} and docs/CHUNK_STATS.md")


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else settings.book_path)
